### ISSUE TITLE
0 byte output

### ISSUE THREAD

**Issue by Oscilloscopy** [gkbrk/apt-encoder#4]
the output file gives 0 bytes when encoded
using: "apt-encode ~/img.pgm > encode.raw"

**Comment by bensimms1** [comment]
what does it do only running "apt-encode"?
also have you tested your compiler
run this: g++ apt-encode.cpp -o apt-encode

**Comment by Oscilloscopy** [comment]
Finally got back to this, and the problem was the way i typed it:
Instead of this,
./apt-encode ~/test.pgm ~/test.pgm > encode.raw
its supposed to be:
./apt-encode ./test.pgm ./test.pgm > encode.raw
(Im using cygwin)
